### ISSUE TITLE
Pressure and feels temp

### ISSUE THREAD

**Issue by tikismoke** [fritz-smh/domogik-plugin-weather#3]
Pressure is incorrect and feels temp show me 61°c.

**Comment by fritz-smh** [comment]
I have the same also. Since the api upgrade on yahoo side, the plugin need to be upgraded :(

<div>-------- Message d'origine --------</div><div>De : tikismoke notifications@github.com </div><div>Date :2016/04/16  16:07  (GMT+01:00) </div><div>À : fritz-smh/domogik-plugin-weather domogik-plugin-weather@noreply.github.com </div><div>Objet : [fritz-smh/domogik-plugin-weather] Pressure and feels temp (#3) </div><div>
</div>Pressure is incorrect and feels temp show me 61°c.

**Comment by fritz-smh** [comment]
Should be fixed in 0.5
Please upgrade domogik in the develop branch and recreate a new device to get pressure in the appropriate unit
